version: "3.2"
services:
  web:
    build: ./web/
    container_name: 'ticket-booking-app-web'
    depends_on:
        - database
    ports:
        - 8080:8080
  consumer:
    build: ./consumer/
    container_name: 'ticket-booking-app-consumer'
    depends_on:
        - web
        - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'ticket-booking-app-rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/rabbitmq/log/:/var/log/rabbitmq
  database:
    image: postgres
    container_name: 'ticket-booking-app-postgres'
    restart: always
    volumes:
        - '/data/pg-data:/var/lib/postgresql/data'
    environment:
        POSTGRES_PASSWORD: pwd1234
    ports:
        - 5432:5432