version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/rabbitmq/log/:/var/log/rabbitmq
  database:
    image: postgres
    restart: always
    volumes:
        - '/data/postgres-data:/var/lib/postgresql/data'
    environment:
        POSTGRES_PASSWORD: pwd1234
    ports:
        - 5432:5432